import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "language_name": "English",
          "obtitle1": "Welcome",
          "obsubtitle1": "Embark on a journey of imagination\nwith Wixpod.",
          "obtitle2": "Supporting Global Storytellers",
          "obsubtitle2": "With every subscription, we provide\ncompensation to writers worldwide.",
          "obtitle3": "Explore Content",
          "obsubtitle3": "Explore various content from\nall over the world.",
          "Skip": "Skip",
          "Login": "Login",
          "Login_no_account": "Don't have an account ?",
          "Login_have_account": "already have an account ?",
          "Login_guest": "Please Login For More Services",
          "Welcome_Back": "Welcome Back",
          "Login_system": "Welcome to the best service provider system!",
          "EmailAddress": "Email Address",
          "EnterEmail": "Enter valid email!",
          "EmptyEmail": "Please enter email!",
          "Password": "Password",
          "EnterPassword": "Enter valid password!",
          "EmptyPassword": "Please enter password!",
          "Login_Forget": "Forget passsword?",
          "Forgot_Forgotpass": "Forgot Password",
          "Send": "Send",
          "Backtologin": "Back To Login",
          "Register": "Register",
          "SignUp": "Sign Up",
          "Name": "Name",
          "ConfirmPassword": "Confirm Password",
          "Home": "Home",
          "Library": "Library",
          "Search_stories": "Search Stories",
          "Favourite": "Favourite",
          "Profilescreen": "Profile Screen",
          "Username": "User Name",
          "Gmail": "Gmail",
          "PhoneNumber": "Phone Number",
          "Author": "Authors",
          "Stories": "Stories",
          "Downloads": "Downloads",
          "Settings": "Settings",
          "Logout": "Logout",
          "ShareApp": "Share App",
          "PrivacyPolicy": "Privacy Policy",
          "AboutUs": "About Us",
          "About": "About",
          "Review": "Review",
          "Summary": "Summary",
          "OverallRatings": "Overall Ratings",
          "StartReading": "Start Reading",
          "Duration": "Duration",
          "PlayerScreen": "PlayerScreen",
          "Profilesuccessfullyupdated": "Profile successfully updated",
          "Guest": "Guest",
          "Update": "Update",
          "Playlist": "Play List",
          "TrendingStories": "Trending Stories",
          "Company": "Company",
          "By": "By : ",
          "Email": "Email",
          "Developer_by": "Developer by",
          "Website": "Website",
          "Contacts": "Contacts",
          "App_Version": "App Version",
          "App_Name": "App Name",
          "See_All": "See All",
          "Our_Top_Picks": "Our Top Picks",
          "No_Favourite_Stories": "No Favourite Stories...",
          "Privacy_Policy": "Privacy Policy",
          "No_Stories_Download": "No Stories Download",
          "Sign_In": "Sign In",
          "No_Search_Results": "No Search Results",
          "Next": "Next",
          "Done": "Done",
          "No_Data": "No Data...",
          "Read_Story": "Read Story",
          "Enter_Name": "Enter Name",
          "Name_is_empty": "Name is empty",
          "Phone_Number": "Phone Number",
          "Latest_Stories": "Latest Stories",
          "Enter_Both_Password_are_Same": "Enter Both Password are Same!",
          "Download_Progress": "Please Wait Until Download Finish",
          "AreyouSure_Logout": "Are you sure want to logout?",
          "Cancel": "Cancel",
          "delete": "Delete account",
          "are_you_sure_to_delete_account": "Are you sure to delete\nyour account ?",
          "delete_account": "Delete account",
          "Language": "Language",
          "Error": "Error",
          "NoImageselected": "No Image selected",
          "Readmore": "Read more",
          "Accept": "Accept",
          "Decline": "Decline",
          "Terms": "Terms & Conditions",
          "ChooseLanguage": "Choose Language",
          "Subscription": "Subscription",
          "Activated": "Activated",
          "Buy Plan": "Buy Plan",
          "Add": "Add",
          "Family Members :": "Family Members :",
          "Numberisempty :": "Phone number is empty!",
          "Discover": "Discover",
          "Search": "Search",
          "Reading": "Reading",
          "Specialcharactersnot": "Special characters are not allowed !!",
          "signinwith": "Sign in with",
          "Storyname": "Story name",
          "Storyartist": "Story artist",
          "Storytitle": "Story title",
          "Filecorrupted": "This audio file is corrupted!",
          "Exitapp": "Exit App",
          "Exitthisapp": "Do you want to exit this app?",
          "No": "No",
          "Yes": "Yes",
          "Dearuser":
              "Dear Wixpod user, to continue enjoying our app, please take a moment to review and accept our Privacy Policy and Terms & Conditions. Your compliance ensures a safe and enjoyable experience. Thank you! ",
          "Verifyinguser": "Verifying user...",
          "dis1":
              "Subscribers gain unlimited access to a vast library of storybooks, allowing them to explore various authors, and topics without restrictions.",
          "dis2":
              "Users can download storybooks for offline listening, enabling them to enjoy their favorite titles even without an internet connection, perfect for commuting or traveling.",
          "dis3": "Subscribers can enjoy storybooks without interruptions from ads, creating a seamless and immersive listening experience.",
          "dis4":
              "Users can add multiple family members to the same subscription at a discounted rate compared to individual subscriptions. This allows families to enjoy storybooks together while saving money.",
          "Reload": "Reload",
          "tryagain": "Oops! We couldn\'t fetch your subscription details. Please try again"
        },
        'fr_FR': {
          "language_name": "français",
          "obtitle1": "Bienvenu",
          "obsubtitle1": "Embarquez pour un voyage d'imagination\navec Wixpod.",
          "obtitle2": "Soutenir les conteurs mondiaux",
          "obsubtitle2": "Avec chaque abonnement, nous offrons\nune rémunération aux écrivains du monde entier.",
          "obtitle3": "Explorer le contenu",
          "obsubtitle3": "Explorez divers contenus du partout\ndans le monde.",
          "Skip": "Sauter",
          "Login": "Connectez-vous",
          "Login_no_account": "Vous n'avez pas de compte ?",
          "Login_have_account": "Vous avez déjà un compte ?",
          "Login_guest": "Veuillez vous connecter pour plus de services",
          "Welcome_Back": "Bienvenue",
          "Login_system": "Bienvenue dans le meilleur système de fournisseur de services!",
          "EmailAddress": "Adresse courriel",
          "EnterEmail": "Entrez une adresse email valide!",
          "EmptyEmail": "Veuillez entrer votre e-mail!",
          "Password": "Mot de passe",
          "EnterPassword": "Entrez un mot de passe valide!",
          "EmptyPassword": "Veuillez entrer le mot de passe!",
          "Login_Forget": "Oublier l’épée secrète?",
          "Forgot_Forgotpass": "Mot de passe oublié",
          "Send": "Envoyer",
          "Backtologin": "Retour à Connexion",
          "Register": "Registre",
          "SignUp": "S’enregistrer",
          "Name": "Nom",
          "ConfirmPassword": "Confirmer le mot de passe",
          "Home": "Accueil",
          "Library": "Bibliothèque",
          "Search_stories": "Rechercher des histoires",
          "Favourite": "Favori",
          "Profilescreen": "Écran de profil",
          "Username": "Nom d’utilisateur",
          "Gmail": "Gmail",
          "PhoneNumber": "Numéro de téléphone",
          "Author": "Auteurs",
          "Stories": "Histoires",
          "Downloads": "Téléchargements",
          "Settings": "Paramètres",
          "Logout": "Se déconnecter",
          "ShareApp": "Partager l’application",
          "PrivacyPolicy": "Politique de confidentialité",
          "AboutUs": "Qui sommes-nous",
          "About": "A propos",
          "Review": "Avis",
          "Summary": "Résumé",
          "OverallRatings": "Notes globales",
          "StartReading": "Commencer à lire",
          "Duration": "Durée",
          "PlayerScreen": "PlayerScreen",
          "Profilesuccessfullyupdated": "Profil mis à jour avec succès",
          "Guest": "Invités",
          "Update": "Mise à jour",
          "Playlist": "Playlist",
          "TrendingStories": "Histoires tendances",
          "Company": "Compagnie",
          "By": "Par : ",
          "Email": "E-mail",
          "Developer_by": "Développeur par",
          "Website": "Site internet",
          "Contacts": "Contacts",
          "App_Version": "Version de l’application",
          "App_Name": "Nom de l’application",
          "See_All": "Voir tout",
          "Our_Top_Picks": "Nos meilleurs choix",
          "No_Favourite_Stories": "Aucune histoire préférée...",
          "Privacy_Policy": "Politique de confidentialité",
          "No_Stories_Download": "Aucune histoire à télécharger",
          "Sign_In": "Connexion",
          "No_Search_Results": "Aucun résultat de recherche",
          "Next": "Suivant",
          "Done": "Fait",
          "No_Data": "Pas de données...",
          "Read_Story": "Lire l'histoire",
          "Enter_Name": "Entrez le nom",
          "Name_is_empty": "Le nom est vide",
          "Phone_Number": "Numéro de téléphone",
          "Latest_Stories": "Histoires récentes",
          "Enter_Both_Password_are_Same": "Entrez les deux mots de passe sont identiques!",
          "Download_Progress": "Veuillez patienter jusqu'à la fin du téléchargement",
          "AreyouSure_Logout": "êtes-vous sûr de vouloir vous déconnecter?",
          "Cancel": "Annuler",
          "delete": "Supprimer le compte",
          "are_you_sure_to_delete_account": "Êtes-vous sûr de vouloir supprimer\nVotre compte ?",
          "delete_account": "Supprimer le compte",
          "Language": "Langue",
          "Error": "Erreur",
          "NoImageselected": "Aucune image sélectionnée",
          "Readmore": "En savoir plus",
          "Accept": "Accepter",
          "Decline": "Déclin",
          "Terms": "termes et conditions",
          "ChooseLanguage": "Choisissez la langue",
          "Subscription": "abonnement",
          "Activated": "Activé",
          "Buy Plan": "Acheter un forfait",
          "Add": "Ajouter",
          "Family Members :": "Membres de la famille :",
          "Numberisempty :": "Le numéro de téléphone est vide!",
          "Discover": "Découvrir",
          "Search": "Recherche",
          "Reading": "Lisez",
          "Specialcharactersnot": "Les caractères spéciaux ne sont pas autorisés !!",
          "signinwith": "Se connecter avec",
          "Storyname": "Nom de l'histoire",
          "Storyartist": "Artiste d'histoire",
          "Storytitle": "Titre de l'histoire",
          "Filecorrupted": "Ce fichier audio est corrompu!",
          "Exitapp": "Quitter l'application",
          "Exitthisapp": "Voulez-vous quitter cette application?",
          "No": "Non",
          "Yes": "Oui",
          "Dearuser":
              "Cher utilisateur Wixpod, pour continuer à profiter de notre application, veuillez prendre un moment pour consulter et accepter notre politique de confidentialité et nos conditions générales. Votre conformité garantit une expérience sûre et agréable. Merci! ",
          "Verifyinguser": "Vérification de l'utilisateur...",
          "dis1":
              "Subscribers gain unlimited access to a vast library of storybooks, allowing them to explore various authors, and topics without restrictions.",
          "dis2":
              "Les utilisateurs peuvent télécharger des livres d'histoires pour les écouter hors ligne, ce qui leur permet de profiter de leurs titres préférés même sans connexion Internet, ce qui est parfait pour les déplacements domicile-travail ou les voyages.",
          "dis3":
              "Les abonnés peuvent profiter des livres d'histoires sans interruption due aux publicités, créant ainsi une expérience d'écoute fluide et immersive.",
          "dis4":
              "Les utilisateurs peuvent ajouter plusieurs membres de la famille au même abonnement à un tarif réduit par rapport aux abonnements individuels. Cela permet aux familles de profiter de livres d'histoires ensemble tout en économisant de l'argent.",
          "Reload": "Recharger",
          "tryagain": "Oops! Nous n'avons pas pu récupérer les détails de votre abonnement. Veuillez réessayer"
        },
        'da_DA': {
          "language_name": "Danish",
          "obtitle1": "Velkommen",
          "obsubtitle1": "Udforsk forskelligt indhold\nfra hele verden.",
          "obtitle2": "Støtte til globale historiefortællere",
          "obsubtitle2": "Med hvert abonnement yder vi\nkompensation til forfattere over hele verden.",
          "obtitle3": "Udforsk indhold",
          "obsubtitle3": "Udforsk forskelligt indhold\nfra hele verden.",
          "Skip": "Springe",
          "Login": "Log på",
          "Login_no_account": "Har du ikke en konto?",
          "Login_have_account": "Har du allerede en bruger ?",
          "Login_guest": "Log venligst ind for flere tjenester",
          "Welcome_Back": "Velkommen tilbage",
          "Login_system": "Velkommen til det bedste tjenesteudbydersystem!",
          "EmailAddress": "E-mail-adresse",
          "EnterEmail": "Indtast gyldig e-mail!",
          "EmptyEmail": "Indtast venligst e-mail!",
          "Password": "Kodeord",
          "EnterPassword": "Indtast gyldig adgangskode!",
          "EmptyPassword": "Indtast venligst adgangskode!",
          "Login_Forget": "Glem adgangssværd?",
          "Forgot_Forgotpass": "Glemt adgangskode",
          "Send": "Sende",
          "Backtologin": "Tilbage til login",
          "Register": "Registrer",
          "SignUp": "Tilmeld dig",
          "Name": "Navn",
          "ConfirmPassword": "Bekræft adgangskode",
          "Home": "Hjem",
          "Library": "Bibliotek",
          "Search_stories": "Søg historier",
          "Favourite": "Favorit",
          "Profilescreen": "Profil skærm",
          "Username": "Brugernavn",
          "Gmail": "Gmail",
          "PhoneNumber": "Telefonnummer",
          "Author": "Forfattere",
          "Stories": "Historier",
          "Downloads": "Downloads",
          "Settings": "Indstillinger",
          "Logout": "Log ud",
          "ShareApp": "Del app",
          "PrivacyPolicy": "Håndtering af persondata",
          "AboutUs": "Om os",
          "About": "Omtrent",
          "Review": "Anmeldelse",
          "Summary": "Resumé",
          "OverallRatings": "Samlet bedømmelser",
          "StartReading": "Begynd at læse",
          "Duration": "Varighed",
          "PlayerScreen": "PlayerScreen",
          "Profilesuccessfullyupdated": "Profilen blev opdateret",
          "Guest": "Gæst",
          "Update": "Opdatering",
          "Playlist": "Afspilningsliste",
          "TrendingStories": "Trendende historier",
          "Company": "Firma",
          "By": "Ved : ",
          "Email": "E-mail",
          "Developer_by": "Udvikler af",
          "Website": "Hjemmeside",
          "Contacts": "Kontakter",
          "App_Version": "App-version",
          "App_Name": "App-navn",
          "See_All": "Se alt",
          "Our_Top_Picks": "Vores foretrukne valg",
          "No_Favourite_Stories": "Ingen yndlingshistorier...",
          "Privacy_Policy": "Håndtering af persondata",
          "No_Stories_Download": "Download ingen historier",
          "Sign_In": "Log på",
          "No_Search_Results": "Ingen søgeresultater",
          "Next": "Næste",
          "Done": "Gjort",
          "No_Data": "Ingen data...",
          "Read_Story": "Læs historie",
          "Enter_Name": "Indtast navn",
          "Name_is_empty": "Navnet er tomt",
          "Phone_Number": "Telefonnummer",
          "Latest_Stories": "Seneste historier",
          "Enter_Both_Password_are_Same": "Indtast begge adgangskoder er ens!",
          "Download_Progress": "Vent venligst, indtil download er færdig",
          "AreyouSure_Logout": "Er du sikker på at vil logge ud?",
          "Cancel": "Aflyse",
          "delete": "Slet konto",
          "are_you_sure_to_delete_account": "Er du sikker på at slette\ndin konto ?",
          "delete_account": "Slet konto",
          "Language": "Sprog",
          "Error": "Fejl",
          "NoImageselected": "Intet billede valgt",
          "Readmore": "Læs mere",
          "Accept": "Acceptere",
          "Decline": "Nedgang",
          "Terms": "Vilkår og Betingelser",
          "ChooseLanguage": "Vælg sprog",
          "Subscription": "abonnement",
          "Activated": "Aktiveret",
          "Buy Plan": "Køb plan",
          "Add": "Tilføje",
          "Family Members :": "Familie medlemmer :",
          "Numberisempty :": "Telefonnummeret er tomt!",
          "Discover": "Opdage",
          "Search": "Søg",
          "Reading": "Læsning",
          "Specialcharactersnot": "Specialtegn er ikke tilladt !!",
          "signinwith": "Log ind med",
          "Storyname": "Historiens navn",
          "Storyartist": "Historiekunstner",
          "Storytitle": "Historiens titel",
          "Filecorrupted": "Denne lydfil er beskadiget!",
          "Exitapp": "Afslut app",
          "Exitthisapp": "Vil du afslutte denne app?",
          "No": "Ingen",
          "Yes": "Ja",
          "Dearuser":
              "Kære Wixpod-bruger, for at fortsætte med at nyde vores app, skal du bruge et øjeblik på at gennemgå og acceptere vores privatlivspolitik og vilkår og betingelser. Din overholdelse sikrer en sikker og fornøjelig oplevelse. Tak skal du have! ",
          "Verifyinguser": "Bekræfter bruger...",
          "dis1":
              "Abonnenter får ubegrænset adgang til et stort bibliotek af historiebøger, der giver dem mulighed for at udforske forskellige forfattere og emner uden begrænsninger.",
          "dis2":
              "Brugere kan downloade historiebøger til offline lytning, så de kan nyde deres yndlingstitler selv uden internetforbindelse, perfekt til pendling eller rejser.",
          "dis3": "Abonnenter kan nyde historiebøger uden afbrydelser fra annoncer, hvilket skaber en problemfri og fordybende lytteoplevelse.",
          "dis4":
              "Brugere kan tilføje flere familiemedlemmer til det samme abonnement til en nedsat pris sammenlignet med individuelle abonnementer. Dette giver familier mulighed for at nyde historiebøger sammen, mens de sparer penge.",
          "Reload": "Genindlæs",
          "tryagain": "Ups! Vi kunne ikke hente dine abonnementsoplysninger. Prøv igen"
        },
      };
}
