// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEk1thhwghEvaVDXb1MWL1n1IRbUz-3U',
    appId: '1:454535986794:android:cb52f4b3b3d85b4f429413',
    messagingSenderId: '454535986794',
    projectId: 'wixpod',
    storageBucket: 'wixpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxITcT6hEhTk0HsCxbI-iPn5aDG3mVjNA',
    appId: '1:454535986794:ios:e1da9b19d5c2f6d6429413',
    messagingSenderId: '454535986794',
    projectId: 'wixpod',
    storageBucket: 'wixpod.appspot.com',
    androidClientId: '454535986794-en6g414pl3vmc4l52ldhoav346api8ha.apps.googleusercontent.com',
    iosClientId: '454535986794-f04kv6j6gtihdlldi87t4nnjt07tngsq.apps.googleusercontent.com',
    iosBundleId: 'com.wixpod',
  );
}
